// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: avg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumsRequest) Reset() {
	*x = NumsRequest{}
	mi := &file_avg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumsRequest) ProtoMessage() {}

func (x *NumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumsRequest.ProtoReflect.Descriptor instead.
func (*NumsRequest) Descriptor() ([]byte, []int) {
	return file_avg_proto_rawDescGZIP(), []int{0}
}

func (x *NumsRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AvgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgResponse) Reset() {
	*x = AvgResponse{}
	mi := &file_avg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgResponse) ProtoMessage() {}

func (x *AvgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgResponse.ProtoReflect.Descriptor instead.
func (*AvgResponse) Descriptor() ([]byte, []int) {
	return file_avg_proto_rawDescGZIP(), []int{1}
}

func (x *AvgResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_avg_proto protoreflect.FileDescriptor

const file_avg_proto_rawDesc = "" +
	"\n" +
	"\tavg.proto\x12\x03avg\"\x1f\n" +
	"\vNumsRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\"%\n" +
	"\vAvgResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2<\n" +
	"\n" +
	"AvgService\x12.\n" +
	"\x06AvgCal\x12\x10.avg.NumsRequest\x1a\x10.avg.AvgResponse(\x01B*Z(github.com/jayanthsharabu/grpc/avg/protob\x06proto3"

var (
	file_avg_proto_rawDescOnce sync.Once
	file_avg_proto_rawDescData []byte
)

func file_avg_proto_rawDescGZIP() []byte {
	file_avg_proto_rawDescOnce.Do(func() {
		file_avg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avg_proto_rawDesc), len(file_avg_proto_rawDesc)))
	})
	return file_avg_proto_rawDescData
}

var file_avg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avg_proto_goTypes = []any{
	(*NumsRequest)(nil), // 0: avg.NumsRequest
	(*AvgResponse)(nil), // 1: avg.AvgResponse
}
var file_avg_proto_depIdxs = []int32{
	0, // 0: avg.AvgService.AvgCal:input_type -> avg.NumsRequest
	1, // 1: avg.AvgService.AvgCal:output_type -> avg.AvgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avg_proto_init() }
func file_avg_proto_init() {
	if File_avg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avg_proto_rawDesc), len(file_avg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avg_proto_goTypes,
		DependencyIndexes: file_avg_proto_depIdxs,
		MessageInfos:      file_avg_proto_msgTypes,
	}.Build()
	File_avg_proto = out.File
	file_avg_proto_goTypes = nil
	file_avg_proto_depIdxs = nil
}
